// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkuCfVyV8SXVx_-JKSfwfJQGKKsxrla0M',
    appId: '1:700733171620:web:4083eb1ea4365b87220331',
    messagingSenderId: '700733171620',
    projectId: 'glamour-salon-5007c',
    authDomain: 'glamour-salon-5007c.firebaseapp.com',
    storageBucket: 'glamour-salon-5007c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPf4wFKlew-DeNlog-lxPJ7IHmUzRadjI',
    appId: '1:700733171620:android:3473aae26a50074a220331',
    messagingSenderId: '700733171620',
    projectId: 'glamour-salon-5007c',
    storageBucket: 'glamour-salon-5007c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqOTqIJHYfXilTau5FjkFqxTMEHCYulCM',
    appId: '1:700733171620:ios:3e0aa7f44fe171c4220331',
    messagingSenderId: '700733171620',
    projectId: 'glamour-salon-5007c',
    storageBucket: 'glamour-salon-5007c.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqOTqIJHYfXilTau5FjkFqxTMEHCYulCM',
    appId: '1:700733171620:ios:3e0aa7f44fe171c4220331',
    messagingSenderId: '700733171620',
    projectId: 'glamour-salon-5007c',
    storageBucket: 'glamour-salon-5007c.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkuCfVyV8SXVx_-JKSfwfJQGKKsxrla0M',
    appId: '1:700733171620:web:2ac9644b01ccf62c220331',
    messagingSenderId: '700733171620',
    projectId: 'glamour-salon-5007c',
    authDomain: 'glamour-salon-5007c.firebaseapp.com',
    storageBucket: 'glamour-salon-5007c.firebasestorage.app',
  );
}
